### ISSUE TITLE
[Draft for jhlite] Add a search module bar to the landscape screen

### ISSUE THREAD

**Issue by renanfranca** [renanfranca/renanfranca#2]
### Prerequisite

- [ ] Add a button to hide the properties form component (needed on small device screens)
- [ ] Memorize in local storage the hide/show preference options selected by the user from the minimap/presetConfiguration/propertiesForm components. This will avoid the annoying situation of having to hide or show components every time they press F5 or access JHipster Lite. `ComponentsVisibilityRepository`-> `LocalStorageComponentsVisibilityRepository`

### TODO

- [ ] (work in progress...)

### Demo of the prototype to show the viability of this feature

The recorded video missed some frames and is lagging, but it's super smooth to use. Please ignore the search button, as it wasn't needed.

https://github.com/user-attachments/assets/d3ab75c1-0138-4628-a67e-d769ba6be938
